# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys]
    -   id: check-ast # make sure all python code is valid
    -   id: end-of-file-fixer # files are either empty or end with newline
    -   id: trailing-whitespace
    -   id: detect-private-key
-   repo: https://github.com/psf/black # python black, fixes format issues.
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
-   repo: https://github.com/asottile/blacken-docs # Python code blocks in docs
    rev: 1.19.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black>=21.7b0]
-   repo: https://github.com/PyCQA/flake8 # reports deviations from PEP8
    rev: '7.1.1'
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy # static type checker
    rev: v1.12.1
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
-   repo: https://github.com/PyCQA/isort # sorts imports
    rev: 5.13.2
    hooks:
    -   id: isort
-   repo: https://github.com/jorisroovers/gitlint
    rev:  v0.19.1
    hooks:
    -   id: gitlint
        args: [--ignore,B6,--msg-filename]
